### Submit Orders
POST http://localhost:4004/browse/Orders
Content-Type: application/json
Authorization: Basic am9yZ2Uuc2FuY2hvQGdtYWlsLmNvbTpxSDhWSHdYbXVVbmd5eVM=

{
    "OrderNo":"2019-09...",
    "Items": [
        {   
            "book_ID":201,
            "amount" :5
        }
    ]
}

### Check books entity that stock was reduced
GET http://localhost:4004/admin/Books(201)